apiVersion : apps/v1
kind: Deployment
metadata:
  name: kube 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube 
    spec:
      containers:
        - name: kube 
          image: dockerappwt.azurecr.io/kube
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
          - containerPort: 80
          envFrom:
          - secretRef:
              name: vars